"""empty message

Revision ID: 0b7aae0c41e1
Revises: ab66aba2dd9e
Create Date: 2017-04-11 17:44:39.023000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7aae0c41e1'
down_revision = 'ab66aba2dd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('token', sa.String(length=200), nullable=True))
    op.create_unique_constraint(None, 'user_profile', ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_column('user_profile', 'token')
    # ### end Alembic commands ###
