"""empty message

Revision ID: 6abfe2211078
Revises: 7eb0c365d526
Create Date: 2017-04-07 12:30:37.030000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6abfe2211078'
down_revision = '7eb0c365d526'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_email_address_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['email'])
    op.drop_column('user_profile', 'email_address')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email_address', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_email_address_key', 'user_profile', ['email_address'])
    op.drop_column('user_profile', 'email')
    # ### end Alembic commands ###
