"""empty message

Revision ID: 7eb0c365d526
Revises: 414777a4181e
Create Date: 2017-04-07 12:15:14.635000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb0c365d526'
down_revision = '414777a4181e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('email_address', sa.String(length=80), nullable=True))
    op.drop_constraint(u'user_profile_username_key', 'user_profile', type_='unique')
    op.create_unique_constraint(None, 'user_profile', ['email_address'])
    op.drop_column('user_profile', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profile', sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.create_unique_constraint(u'user_profile_username_key', 'user_profile', ['username'])
    op.drop_column('user_profile', 'email_address')
    # ### end Alembic commands ###
