"""empty message

Revision ID: 9cfce2548a6a
Revises: d47dc1a2c081
Create Date: 2017-04-07 21:42:44.973000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cfce2548a6a'
down_revision = 'd47dc1a2c081'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'wishlist_item_webaddress_key', 'wishlist_item', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(u'wishlist_item_webaddress_key', 'wishlist_item', ['webaddress'])
    # ### end Alembic commands ###
