"""empty message

Revision ID: ab66aba2dd9e
Revises: 9cfce2548a6a
Create Date: 2017-04-08 20:38:14.494000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab66aba2dd9e'
down_revision = '9cfce2548a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('thumbnail', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_item', 'thumbnail')
    # ### end Alembic commands ###
