"""empty message

Revision ID: d47dc1a2c081
Revises: dc3e95b95da1
Create Date: 2017-04-07 21:32:14.532000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd47dc1a2c081'
down_revision = 'dc3e95b95da1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('id', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wishlist_item', 'id')
    # ### end Alembic commands ###
