"""empty message

Revision ID: dc3e95b95da1
Revises: a45486a45203
Create Date: 2017-04-07 21:14:06.972000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc3e95b95da1'
down_revision = 'a45486a45203'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('owner', sa.Integer(), nullable=True))
    op.drop_column('wishlist_item', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wishlist_item', sa.Column('id', sa.INTEGER(), nullable=False))
    op.drop_column('wishlist_item', 'owner')
    # ### end Alembic commands ###
